Fliplet/fliplet-widget-form-builder

- js/libs/builder.js
In some instances where the form is too big and the page has scroll, the `Fliplet.Studio.emit('reload-widget-instance', widgetId);` isn't enough.
So the refresh of the page preview is called after saving with `Fliplet.Studio.emit('reload-page-preview');`.
Still related to this: https://github.com/Fliplet/fliplet-studio/issues/978
> Forced refresh to fix widget disappearing in edit mode

- js/components/checkbox.js
- js/libs/form.js
ref https://github.com/Fliplet/fliplet-studio/issues/1460
---
This is mainly for existing forms or widget instances that incorrectly give a non-array value as default or existing value for any checkbox field.
> make sure given value for checkbox is an array

- js/libs/builder.js
Reason of the issue: a data source can have hooks set up by multiple forms (hence different `widgetInstanceId`).
ref https://github.com/Fliplet/fliplet-studio/issues/1510
> only update hook when found

- js/libs/builder.js
ref https://github.com/Fliplet/fliplet-studio/issues/1532
---
**Identifiers may be any unicode character except for the following:**
> Whitespace ! " # % & ' ( ) * + , . / ; < = > @ [ \ ] ^ ` { | } ~
To reference a property that is not a valid identifier, you can use segment-literal notation, `[`.
http://handlebarsjs.com/expressions.html
> escape for handlebars variables

- js/libs/form.js
I didn't find any other occurrence looking for `[a-z]+\(\) ?{`.
> one more fix for ie11

- js/build.templates.js
- templates/components/field.build.hbs
This makes it easier to hide a field through custom:
```js
$('[data-field="Question 1"]').hide();
```
Result:
> Adds data-field to .form-group container to help identify containers

- build.html
- js/libs/form.js
Two new methods added to form fields:
- `change(fn [,runOnBind = true])` registers a function to be called whenever the field value changes
- `toggle(bool)` shows and hides the field, also reverting its value to the default value. Field will also not be posted and progress won't be saved
```js
Fliplet.FormBuilder.get().then(function (form) {
// registers a callback to be fired whenever the field value changes
form.field('Question 1').change(function (val) {
// only show / enable this field when val is "foo"
// works like jQuery "toggle", which evaluates the argument as a "truthy" boolean.
form.field('Question 2').toggle(val === 'foo');
});
});
```
> new events and listeners

- css/builder.css
**Override Studio UI**
Before:
After
> Small tweak to UI

- js/libs/core.js
Because we changed the navstack reference created by the file picker in https://github.com/Fliplet/fliplet-widget-file-picker/pull/25 we needed to update the code to be able to open the file manager in the correct folder
> Changed to different navstack reference

- js/libs/form.js
if the value is not a string we cannot use `replace`.
> fix for non-numeric field value

- css/form.css
The Bootstrap class `.container-fluid` is being manipulated by the form builder widget. This should not be the case and it does not appear the form builder is relying on it.
This results in left & right paddings being added to a page simply because a form builder is dropped onto a page.
This 12.5% left/right padding is removed in this PR.
> Ensures padding adjustment is not unnecessarily applied to .container-fluid

- widget.json
ref https://github.com/Fliplet/fliplet-e2e-tests/issues/141
turns out tinymce is being used by the interface here https://github.com/Fliplet/fliplet-widget-form-builder/blob/master/js/libs/builder.js#L834-L835
> missing reference

- css/builder.css
- js/build.templates.js
- js/components/wysiwyg.js
- templates/components/wysiwyg.build.hbs
This fixes an issue where WYSIWYG form field is not draggable in the interface because Sortable doesn't work when the draggable items includes an iFrame.
> Replace TinyMCE iframe with a ghost container in the widget interface

- css/builder.css
- js/components/wysiwyg.js
- widget.json
- Renames **WYSIWYG editor** field to **Rich text**
- Moves **WYSIWYG editor** field to under **Multiple line input** field in the **Text inputs** category
- Fixes an issue with **WYSIWYG editor** field that created horizontal scrolling
> Various fixes with WYSIWYG editor field

- css/form.css
> Fixes issue with date picker UI being too wide

- js/components/wysiwyg.js
Ref. Items 1, 7-9 in https://github.com/Fliplet/fliplet-studio/issues/3257
- text area keeps expanding, has padding at the bottom:
- When you add it to a screen it automatically focusses the cursor on itself, this shouldn't happen. 
- By default it is setting a font size, it shouldn't, otherwise it looks different to the rest of the content on the screen e.g. LFD displays its output.
- on submission the preview shows the HTML code:
> Fixes various issues with WYSIWYG field

- js/libs/builder.js
Ref. https://sentry.io/fliplet/production-widgets-interface/issues/647695190/?query=is:unresolved%20com.fliplet.form-builder
Haven't been able to verify the issue is definitely occurring but based on the Sentry error and that `node.remove()` isn't supported on IE, I'm guessing this should do the trick of resolving the Sentry error.
> Fixes issue when fields can't be added on IE

- js/libs/form.js
Issue: the template(s) from the formbuilder were getting compiled and altered hence using them a second time would have lost the handlebars templated code.
ref https://github.com/Fliplet/fliplet-studio/issues/3334 https://github.com/Fliplet/fliplet-studio/issues/3088
> fixes for composing emails twice

- js/libs/form.js
Ref. https://github.com/Fliplet/fliplet-api/pull/3078
Ref. https://github.com/Fliplet/fliplet-studio/issues/3696
Form saving will now wait for acknowledgement before returning control to the user.
> Forms will now wait for acknowledgement before returning control to user

- js/components/time.js
We had old time format entries in some data sources like: `11:36 PM`, while now, time is logged correctly as `23:36`.
This PR will handle old records and re-format them to the correct format if needed.
Ref.https://github.com/Fliplet/fliplet-studio/issues/3592
> Added conditional time reformatting

- js/components/date.js
This fixes the weird issue where selecting the exact same date from the jquery ui datepicker changes its format.
Ref. https://github.com/Fliplet/fliplet-studio/issues/3645
> Fixed datepicker format

- js/components/checkbox.js
ref https://github.com/Fliplet/fliplet-studio/issues/3743
> Verify the submitted value for checkbox fields are kept in the order as they appear in the form (rather than the order in which the user selected them)
> sort selected options for checkbox fields

- css/form.css
...in order to improve radio UI positioning -- because FontAwesome characters aren't consistent in how it's positioned due to character height, line height etc.
Ref. https://github.com/Fliplet/fliplet-studio/issues/3731
> Stops using FontAwesome for radio UI

- js/libs/form.js
As per GIF below, fixes an issue where the form does not correctly reload its data (both UI state and inputs) after fetching an entry to update.
> Force form update on entry load

- js/libs/form.js
These helpers will be used by **App Templates**.
ref https://github.com/Fliplet/fliplet-studio/issues/4349
---
Proper docs will follow via CLI docs.
```js
// Get value
var value = form.field('field-1').get();
// Set value
form.field('field-1').set({ source: 'profile', key: 'email' })
form.field('field-1').set({ source: 'query', key: 'sessionId' })
form.field('field-1').set({ source: 'storage', key: 'foo' })
form.field('field-1').set({ source: 'appStorage', key: 'foo' })
form.field('field-1').set('bar')
form.field('field-1').set(function () { return Promise.resolve('bar') })
```
> helpers to set field values easily

- js/build.templates.js
- js/components/number.js
- templates/components/number.build.hbs
- the input type will be set to `text`
- the input will only allow numbers, `-` and `.`
- the input type will be set to `number`
- the input will only allow numbers and `.` (this is for web only)
> better validation on input number

- interface.html
- js/libs/builder.js
@squallstar 
Form settings related to a data source should only be available when a data source has been selected
No ref to the Github issue
> Hide data source settings

- js/components/file.js
@squallstar 
Added destroyed lifecycle method in file.js.
P.S. I know that using 'length = 0' for emptying array is not the best practice, but other methods do not work.  
ref Fliplet/fliplet-studio#3786
ref Fliplet/fliplet-studio#3787
> #65 The selected file is saved in the "Attach a file" field after submitting the form #3787 #3786

- css/form.css
@squallstar 
ref https://github.com/Fliplet/fliplet-studio/issues/3239
> Date picker UI render is clipped on the viewport edges

- js/libs/form.js
@squallstar @tonytlwu 
**Fixed behavior:**
When you use the form with a date picker and rich text (only in this sequence) form doesn't submit in IE11 and Edge. Now it submits and shows the correct message.
ref Fliplet/fliplet-studio#4790
> Fixes an issue where Rich Text field wasn't submitting when there's a Datepicker in the same form

- interface.html
@tonytlwu @squallstar 
Fliplet/fliplet-studio#3847
Updated message in the form template
> Updated message in the form template

- js/libs/builder.js
@tonytlwu @squallstar 
Fliplet/fliplet-studio#4827
Changed place where TinyMCE is initiated. Now it initiates when the user clicks on the Setting button. Now should work as expected.
> Changed place where TinyMCE is initiated

- js/libs/builder.js
@tonytlwu @squallstar 
Fliplet/fliplet-studio#4827
Added destroyed method for TinyMCE after the user leaves the settings tab. Now bug should not occur.
> Added tinymce destroyed method

- js/libs/form.js
```js
// get
var options = form.field('foo').options()
// set 
form.field('foo').options([1,2,3])
// reference $vm instance (follows same pattern as form.instance)
form.field('foo').instance
```
> Support for reading list of options on a field and getting the field vue instance

- js/libs/form.js
Changes made via `field.set()` will now trigger `field.change(fn)` if the value has changed.
> Support for triggering change events when the value of a field changes via field.set

- js/libs/form.js
@tonytlwu @squallstar @sofiiakvasnevska 
Fliplet/fliplet-studio#5222
Fliplet/fliplet-studio#5227
If the value set for checkbox it converts the value to array if it is a string and removes duplicates if it is an array.
5222
5227
> User not can enter value for checkbox in string form, dublicate value will be removed 

- js/libs/form.js
@tonytlwu @squallstar @sofiiakvasnevska 
Fliplet/fliplet-studio#5221
Added force blur on all fields after clear which saves them.
> Clear button now works correctly

- js/libs/form.js
@tonytlwu @squallstar @sofiiakvasnevska 
Fliplet/fliplet-studio#5200
Added check to values when user setting options using code.
> If user changes options using setting code, previously selected value will be cleared if they do not correspont to new options

- js/libs/builder.js
Fliplet/fliplet-studio#4498
Added omit page property.
> Current page is not added to link provider dropdown

- js/components/buttons.js
https://github.com/Fliplet/fliplet-studio/issues/5313
Added mounted lifecycle hook that assigns name value to label if there is no value.
> Old buttons fields now have label

- js/libs/form.js
https://github.com/Fliplet/fliplet-studio/issues/5277
Added function that saves progress to local storage after updating via field.set() or field.val().
> Form progress is saved after it's updated via field.set() or field.val()

- js/libs/form.js
- Restores behaviour to prior than 971a024 (line https://github.com/Fliplet/fliplet-widget-form-builder/commit/971a0240b3a98450d0f2f99ec56ba9918007f232#diff-aab0ddc8ded3b82294a8d0537f15e112L117)
ref https://github.com/Fliplet/fliplet-studio/issues/5484
> don't update fields when value is undefined

- js/libs/form.js
https://github.com/Fliplet/fliplet-studio/issues/5448
The invalid options are removed before the options are set.
> Invalid options are removed when setting dropdown field options

- js/libs/form.js
Fliplet/fliplet-studio#5448
The invalid options are removed before the options are set.
> Dropdown now accepts number as options

- css/builder.css
https://github.com/Fliplet/fliplet-studio/issues/5654
Moved the TinyMCE source code window up by 70px.
> Tinymce code fix

- js/libs/builder.js
ref https://github.com/Fliplet/fliplet-studio/issues/5775
---
Saving a form was incorrectly removing from the data source columns all columns not contained in the list of fields of the form to be saved.
This is now fixed so that a form never removes existing columns from a data source.
> fixed wrong variable name

- css/form.css
https://github.com/Fliplet/fliplet-studio/issues/4724
Updated rich text styling.
Goes together with this PR https://github.com/Fliplet/fliplet-theme-default/pull/105
> Border properties now affect rich text field

- css/form.css
Fliplet/fliplet-studio#4724
Removed unnecessary box-shadow property.
Look without setting border.
With setting border
> Removed unnecessary box-shadow property

- js/components/url.js
https://github.com/Fliplet/fliplet-studio/issues/5405
Doesn't allow a user to input incorrect URL
https://share.getcloudapp.com/lluy40Rg
This regex works with all domains listed in this [here](http://data.iana.org/TLD/tlds-alpha-by-domain.txt).
> Doesn't allow a user to input incorrect URL

- css/form.css
https://github.com/Fliplet/fliplet-studio/issues/5325
Changed z-index value.
> Date and calendar icons are now visible on ios13

- js/components/file.js
- js/components/image.js
https://github.com/Fliplet/fliplet-studio/issues/5415
The issue was that onChange event was not triggered when the user uploads same image.
> User now can upload recently deleted file

- js/components/wysiwyg.js
https://github.com/Fliplet/fliplet-studio/issues/5514
When the user click the 'Clear' button Rich text will be cleared as other fields
https://share.getcloudapp.com/4gummKAd
> When the user click the 'Clear' button Rich text will be cleared as other fields

- js/components/checkbox.js
- js/interface.templates.js
- templates/configurations/checkbox.interface.hbs
https://github.com/Fliplet/fliplet-studio/issues/5417
Clearing and saving checkbox values now works as expected.
> Fixed checkbox default value behaviour 

- js/build.templates.js
- js/components/url.js
- templates/components/url.build.hbs
https://github.com/Fliplet/fliplet-studio/issues/5405
Checking on submit and deny if not passing the validation
https://share.getcloudapp.com/P8uR5bdq
Changed type to the `text` so when a user inputs a URL of like this `google.com` standard HTML5 check didn't appear.
> Checking on submit and deny if not passing the validation

- js/libs/builder.js
https://github.com/Fliplet/fliplet-studio/issues/5412
We clear the default description only when selecting the template. Afterwards if user sets new description it will be saved correctly.
> Organization form template description is displayed correctly

- js/build.templates.js
- templates/components/email.build.hbs
https://github.com/Fliplet/fliplet-studio/issues/5788
Changes input type to email.
> Email field has right keyboard on native devices

- js/components/buttons.js
https://github.com/Fliplet/fliplet-studio/issues/6087
Allow a user to reset form to its default values
https://share.getcloudapp.com/v1urnkv8
Please merge this [PR](https://github.com/Fliplet/fliplet-widget-form-builder/pull/290) before approving this.
> Allow a user to reset form to its default values

- js/components/wysiwyg.js
- js/libs/form.js
https://github.com/Fliplet/fliplet-studio/issues/6087
Checkbox and rich text values will be restored on clear button press
https://share.getcloudapp.com/7KuR9nkg
Remade old [PR ](https://github.com/Fliplet/fliplet-widget-form-builder/pull/293)so it doesn't need to update handelbars templates.
> Checkbox and rich text values will be restored on clear button press

- js/libs/form.js
ref https://github.com/Fliplet/fliplet-studio/issues/6256
It looks like the code was broken by a commit made by Upplabs back in December 2019: https://github.com/Fliplet/fliplet-widget-form-builder/commit/b258624ef76ecc395f27ec02d5f07507337c32b1#diff-aab0ddc8ded3b82294a8d0537f15e112L162
> fixes checkbox not populating existing values

- js/libs/form.js
ref https://github.com/Fliplet/fliplet-studio/issues/5423
This patch ensures that the form submit event is saved to storage before the screen navigates away on mobile devices.
> wait for analytics to be saved before screen redirect

- js/components/wysiwyg.js
https://github.com/Fliplet/fliplet-studio/issues/6085
Added two new shortcuts for the unordered list to call.
Use `ctrl+shift+8` for Windows and `command+[` for macOS to call bulleted list in the Rich text.
https://share.getcloudapp.com/eDu69wnX
Using this [command](https://www.tiny.cloud/docs-4x/api/tinymce/tinymce.editor/#addshortcut) to add a new shortcut for the TinyMCE.
@upplabs-alex-levchenko @MaksymShokin
> Users can use shortcuts in the Rich text to add an unordered list

- js/components/url.js
https://github.com/Fliplet/fliplet-studio/issues/6328
Updated regex to allow % sign in the URL
> Updated regex to allow % sign in the URL

- js/libs/builder.js
https://github.com/Fliplet/fliplet-studio/issues/6534
Configuration field will be saved after clicking the Done button.
https://streamable.com/pnyaq5
> [Fix] Config save will be saved after clicking Done button

- js/libs/form.js
`field.toggle` currently resets the field value to the initial value when the field is set to be shown. I have therefore added an optional parameter not to change its value when the field is presented back.
ref https://github.com/Fliplet/fliplet-studio/issues/6919
> [Feat] allow field.toggle not to change a field value

- js/components/wysiwyg.js
https://github.com/Fliplet/fliplet-studio/issues/6085
Allow users to set bullet lists by shortcut (for MAC) command + [
https://share.getcloudapp.com/7KuL87Xd
> [Fix] Allow users to set bullet lists by shortcut (for MAC) command + [

- js/components/wysiwyg.js
https://github.com/Fliplet/fliplet-studio/issues/6422
The container will be selected from the current Rich text component.
https://streamable.com/fmycyc
> [Fix] Added correct selection for Rich text

- js/components/image.js
- js/libs/form.js
requires https://github.com/Fliplet/fliplet-api/pull/4332 to be deployed before this is released.
> ID-328 [Feat] Support for sending image names via base64

- js/libs/builder.js
The form templates loading request will now run only when the form isn't configured and the "choose template" UI is shown to the user.
> ID-370 [Chore] Only load templates when form isn't configured

- js/libs/form.js
Avoids saving back URLs that have already been authenticated, which creates security issues among not being accessible anymore when the user logs out.
> ID-469 [Fix] Authenticate images only for displaying thumbnail

- js/components/time.js
OD-244 https://weboo.atlassian.net/browse/OD-244
Autofill time picker value with the current time when it is empty
https://monosnap.com/file/msxievJf5RHLHNhjUzZmYSe4PkpYXw
@upplabs-alex-levchenko @YaroslavOvdii
> OD-244 [Fix] Autofill time picker value with the current time when it is empty

- js/components/wysiwyg.js
Ref. https://weboo.atlassian.net/browse/ID-817
URLs entered via the WYSIWYG source code editor was being converted from absolute URLs:
...to relative paths:
The image works for web apps but doesn't work for native apps. The [newly added configuration](https://stackoverflow.com/questions/3796942) prevents the absolute URLs from being converted to relative paths.
> ID-817 [Fix] Prevent URLs in TinyMCE from converted to relative paths

- interface.html
@sofiiakvasnevska @inna-bieshulia
OD-605 https://weboo.atlassian.net/browse/OD-605
Description
**Problem:** In the form settings, if a user has selected the option to load data from a user's profile, the option to Add new submissions to a data source is hidden.
**Solution:** Added a help block for hints when the option to Add new submissions to a data source is hidden.
Screenshots/screencasts
https://storyxpress.co/video/kt9xvt3pw7wqy6naf
Backward compatibility
Reviewers
> OD-605 [FIX] Hint when hiding option to Add new submissions

- js/libs/builder.js
@romanyosyfiv
OD-669 https://weboo.atlassian.net/browse/OD-669
Follows https://github.com/Fliplet/fliplet-widget-form-builder/pull/424
**Problem**: The [PR](https://github.com/Fliplet/fliplet-widget-form-builder/pull/419) code was mistakenly reverted by [this commit](https://github.com/Fliplet/fliplet-widget-form-builder/pull/424/commits/e1e11ef88f329d8160a6c31f69597b4787195303) from [this PR](https://github.com/Fliplet/fliplet-widget-form-builder/pull/424)
**Solution**: [PR](https://github.com/Fliplet/fliplet-widget-form-builder/pull/419) code has been restored
> OD-669 [Fix] Ensure data source hooks are kept up to date when saving forms

- css/form.css
@romanyosyfiv @inna-bieshulia
OD-643 https://weboo.atlassian.net/browse/OD-643
**Problem:** There is a padding for the button, which is not designed to have a picture inside.
**Solution:** Added a new padding on the right that lengthens the button.
https://storyxpress.co/video/kwdn3tklg6o5s7ppd
> OD-643 [Fix]  Adjusted document and image add-button padding

- js/components/wysiwyg.js
@romanyosyfiv
OD-705 https://weboo.atlassian.net/browse/OD-705
**Problem:** Placeholder value was only updated on reinitialization.
**Solution:** Added a new watcher for the placeholder that writes the value to the form.
www.awesomescreenshot.com/video/7167468?key=0b360b4c2cd79589048c408eb430d05d
> OD-705 [Fix] Update placeholder value in preview

- js/libs/form.js
For some reason it appears that calling `Fliplet.FormBuilder.get()` in custom code gets fired before forms are registered.
I am running some tests to debug the full event loop, but this patch addresses the situation.
Local tests:
> ID-2397 [Fix] Form getters

- js/components/paragraph.js
- js/components/title.js
Form -> Edit form -> Add fields -> Formatting -> Title
Form -> Edit form -> Add fields -> Formatting -> Paragraph
currently showing the code instated of showing the title and paragraph text. We fixed the title and paragraph fields appear with the text as “Title” and “Paragraph” respectively.
[click here](https://weboo.atlassian.net/browse/XOR-327)
**Result**
https://user-images.githubusercontent.com/102005879/181467843-47fab1d5-59d8-4a4e-b689-bcfe06e90576.mp4
**Checklist**
None
None
None
None
> XOR-327 [Fix] Ensure title and paragraph fields appear with the text in form builder

- js/libs/builder.js
- templates/configurations/form.interface.hbs
Widget -> Form -> Edit Form Field -> Save / Cancel 
Implemented logic while editing form field only one set of Save and Cancel button will show.
[JIRA](https://weboo.atlassian.net/browse/XOR-289)
none
none
none
none
> XOR-289 [Feat] Ensure in edit form field only one set of Save/Cancel button showing

- js/components/paragraph.js
- js/components/title.js
Widgets -> Form Widget  -> Add Title from Format section -> Add Input field -> Change name to Title of Input field
Implemented fix so that Formatting Title field allows user to add other field named as Title.
[JIRA](https://weboo.atlassian.net/browse/XOR-415)
[XOR-Test-415.webm](https://user-images.githubusercontent.com/108272606/189140099-a94fb5a5-9851-4b43-abd1-8971788e0e34.webm)
none
none
none
none
> XOR-415 [Fix] Ensuring the Title field allows user to add another field named Title

- js/build.templates.js
- templates/components/signature.build.hbs
Widgets -> Add Form -> Signature Field -> Make field read only
Implemented code to hide edit button for Signature field when it's read only.
JIRA (https://weboo.atlassian.net/browse/XOR-156)
https://user-images.githubusercontent.com/108272606/193843182-1ca6fe7d-c245-47a4-95ff-b64d7bb94951.mp4
None
None
None
> XOR-156 [Fix] Ensure Edit button is not visible for Signature Read only field

- js/libs/form.js
Studio -> Form -> Image/File field
This PR will fix the issue of replacing an existing file/image attached to a form and adding a new one, both are saved to the form after it is submitted. To resolve the problem added the support of `append`
[ID-3296](https://weboo.atlassian.net/browse/ID-3296)
https://github.com/Fliplet/fliplet-widget-form-builder/assets/108272606/fda7e7b7-7d42-427e-a760-6c32621856cc
[ID-3296]: https://weboo.atlassian.net/browse/ID-3296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ID-3296 [FIX] Ensure support added to append in adding files and imges to DS entry

- js/components/url.js
- js/libs/form.js
- ID-3367 [Fix] Allow field(name).$instance to be undefined
- ID-3370 [Fix] Consider the URL as a valid string format if there's no value provided
> Release to Production

- js/libs/form.js
Studio -> Form -> Form Fields
Implemented code, so entry data available on frontend after loading the form with dataSourceEntryId passed to it
[click here](https://weboo.atlassian.net/browse/ID-2845)
**Result**
https://github.com/Fliplet/fliplet-widget-form-builder/assets/108272606/62e5e3c9-d685-4c95-9fd6-2adee0f919e6
**Checklist**
None
None
None
None
> ID-2845 [FEAT] Add afterFormEntryLoad hook for accessing data source entry after it's loaded in a form

- js/components/file.js
- js/components/image.js
Studio -> Form -> Add image / file field
Implemented code, so while adding image in image or file field should not rotate
[ID-2804](https://weboo.atlassian.net/browse/ID-2804)
**Result**
https://github.com/Fliplet/fliplet-widget-chat/assets/108272606/8088196c-f6a5-4595-9fb6-5b9f8ee2fc7d
**Checklist**
None
None
None
None
[ID-2804]: https://weboo.atlassian.net/browse/ID-2804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ID-2804 [FIX] Ensure attached images are not saved with the wrong orientation

- css/form.css
> ID-3677 [FIX] Code scanner btn do not have spacing underneath

- js/components/wysiwyg.js
https://github.com/Fliplet/fliplet-widget-form-builder/assets/128052346/0f02d14c-f459-48a7-a1a9-5c591839d0fc
> ID-3849 [FIX] Ensure to close the toolbar in full screen on mobile preview

- js/components/typeahead.js
- js/libs/form.js
When we are trying to assign a field value from LFD that contains more items than the field max items value, the field triggers an infinite loop.
Splits the field value with the max items count if it is provided.
https://www.loom.com/share/dc7e30b48c0347579afdec4ddd78eed2?sid=9d11d0a6-355e-4bed-9377-3a50686dd9b4
> ID-3993 [FIX] Ensure typeahead not triggers infinite loop

- js/libs/form.js
Ref. https://weboo.atlassian.net/browse/ID-3998
When the form name setting was changed from `form.name` to `form.displayName` ([commit](https://github.com/Fliplet/fliplet-widget-form-builder/commit/446c470724bb366bd04ad753fdbbc275c3df5aad#diff-4afc485ba32b2951dc94b6b24e4a9d40316ffeab9ab059691604291f2d21cf00R378)), [this line](https://github.com/Fliplet/fliplet-widget-form-builder/commit/f235213492a62d66d79fea5b68fc7e7b6812de79#diff-524255b142ab5cdf4d2376cd9ecbc907441103c5db0a458e3bb3e91ce00ac8ffR371) should have been changed to use the `displayName` key as well.
> ID-3998 [Fix] Allow form name to be used correctly for filtering

- js/libs/form.js
https://www.loom.com/share/2acf2a4ed33542f28c47f561c135fe19?sid=42a5b6bf-95d0-4818-8e0a-d4111c4ced54
> ID-4051 [FIX] Ensure to not set empty value to typeahead on form reset

- css/form.css
> ID-3977 [FIX] Move rich text '...' to the right corner on mobile and tablet

- js/components/input.js
- js/libs/form.js
It prevents resetting the value of read-only **field**. This applies to all fields marked as `readonly.`
[ID-4052](https://weboo.atlassian.net/browse/ID-4052)
[ID-4052]: https://weboo.atlassian.net/browse/ID-4052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ID-4052 resetting read only input

- js/components/reorderList.js
- js/libs/core.js
- js/libs/form.js
Fixes these issues: 
- Can’t drag a list item after the first time dragging and dropping it;
- Empty entries are saved to the linked DS if submitting not reordered list;
- The list has the wrong order (default) when loading it through the LFD;
[ID-4037](https://weboo.atlassian.net/browse/ID-4037)
[ID-4037]: https://weboo.atlassian.net/browse/ID-4037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ID-4037 [FIX] Reorder list issues

- js/components/file.js
Fixes the issue when in the form settings is set “When the form is loaded...“ to “Load the data from user's profile“ and the user has saved file, the name of the file is “To be uploaded“ instead of a real file name
###Result
https://www.loom.com/share/c43d9d73af2946179c93d70d04f62429?sid=9a91c41d-0187-48cf-b395-a658d6668d9f
> ID-4193 [FIX] File form field issues

- js/components/date.js
- js/components/time.js
The problem was with condition race - if the field was set to `autofill: 'empty'` and was meant to load data from DS, then the first rendered field (time or date) was emptied after loading DS data. 
I've prevented emptying fields with `autofill: 'empty'` if they are about to load data from DS.
https://weboo.atlassian.net/browse/ID-4239
> ID-4239 [fix] fixed emptying date and time inputs meant to load data from ds

- css/form.css
- js/components/wysiwyg.js
Ensure to have proper height when row count is 1
> ID-4123 [FIX] Field height of the text area is too narrow

- js/components/typeahead.js
> ID-4144 [FIX] Ensure typeahead list appears in the order we type in

- js/components/wysiwyg.js
https://github.com/Fliplet/fliplet-widget-form-builder/assets/128052346/e3163dd0-2383-445d-980d-d63b2374990b
> ID-4122 [FIX] Rich text field additional items layout overlaps for ios native

- js/components/wysiwyg.js
Reverts Fliplet/fliplet-widget-form-builder#654 due to QA fail.
> Revert "ID-4122 [FIX] Rich text field additional items layout overlaps for ios native"

- js/components/typeahead.js
- js/libs/form.js
Form Builder, typeahead.js
This PR ensures Typeahead field saves correctly.
[PS-29](https://weboo.atlassian.net/browse/PS-29)
[PS-29]: https://weboo.atlassian.net/browse/PS-29?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PS-29 [FIX] Ensure Typeahead field saves correctly

- js/libs/builder.js
Form Buider, builder.js
Ensures Rich text field is rendered in Drag and drop accordion of Add fields  overlay after switching between Component settings tabs
[PS-53](https://weboo.atlassian.net/browse/PS-53)
[PS-53]: https://weboo.atlassian.net/browse/PS-53?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PS-53 [FIX] Ensure Rich text field is rendered in Drag and drop accordion of Add fields overlay after switching between settings tabs

- js/components/image.js
Fliiplet Form Builder
Ensures the Image field doesn't trigger a max size error when no max size is specified.
[PS-692](https://weboo.atlassian.net/browse/PS-692)
[PS-692]: https://weboo.atlassian.net/browse/PS-692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PS-692 [FIX] Ensures the Image field doesn't trigger a max size error when no max size is specified.

- js/libs/form.js
Ensures that Prev buttons do not block navigation to the previous slide when required fields are incomplete, all data entered into the form fields is cleared after submitting the entire sequence of forms,  previous and next slide link actions don't lead the user to the end or beginning of the slider.
[DEV-477](https://weboo.atlassian.net/browse/DEV-477)
[DEV-481](https://weboo.atlassian.net/browse/DEV-481)
[DEV-484](https://weboo.atlassian.net/browse/DEV-484)
[DEV-477]: https://weboo.atlassian.net/browse/DEV-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-481]: https://weboo.atlassian.net/browse/DEV-481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-484]: …
> Fix/DEV-477: Ensures previous and next slide link actions don't lead the user to the end or beginning of the slider.

- js/components/geolocation.js
Moves the Geolocation field from the Advanced category to the Location & Map category in the components accordion.
[DEV-508](https://weboo.atlassian.net/browse/DEV-508)
**Checklist**
None
None
None
None
[PS-508]: https://weboo.atlassian.net/browse/PS-508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-508]: https://weboo.atlassian.net/browse/DEV-508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PS-508 [FIX] move geolocation field to location & map category

- js/components/number.js
Validate commas are not present in the numbers form field when decimal numbers are configured.
[PS-690](https://weboo.atlassian.net/browse/DEV-690)
**Checklist**
None
None
None
None
[PS-690]: https://weboo.atlassian.net/browse/PS-690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PS-690 [FIX] validate comma is not present in decimal numbers

- js/libs/form.js
Fliplet Form Builder -> Type Ahead Field
Ensures the values are set and options array is updated accordingly in the typeahead field, when values are set through custom code using FormBuilder's JS API.
[DEV-207](https://weboo.atlassian.net/browse/DEV-207)
[DEV-207]: https://weboo.atlassian.net/browse/DEV-207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PS-207 [FIX] Ensure values are set in typeahead field when not present in initial options
