js/build.templates.js
js/components/image.js
js/interface.templates.js
templates/components/image.build.hbs
templates/configurations/image.interface.hbs

- Works on web
- Not tested on native

[WIP] native image upload

---

js/libs/builder.js

To fix - https://github.com/Fliplet/fliplet-studio/issues/978

Fix form preview disappearing

---

js/components/buttons.js
js/components/horizontalRule.js
js/components/paragraph.js
js/components/title.js
js/libs/builder.js
js/libs/core.js
js/libs/templates.js

Fixes https://github.com/Fliplet/fliplet-studio/issues/985
Fixes https://github.com/Fliplet/fliplet-studio/issues/987
Fixes https://github.com/Fliplet/fliplet-studio/issues/992

Fixes Form Builder issues

---

css/builder.css
css/form.css
interface.html
js/libs/builder.js
js/libs/form.js

- Fixes issue with reordering when exists required fields
- Fixes issue with saving fields
- Better handling of email templates
- Colour tweaks
- Better submission handling of actions

Fixes several issues

---

js/libs/templates.js

ref https://github.com/Fliplet/fliplet-studio/issues/1288

don't load organization templates when not in organization

---

js/components/password.js
js/libs/builder.js

fixes https://sentry.io/fliplet/widgets-interface/issues/329356195/
cc @hcarneiro

fix for missing property on image and file fields

---

js/build.templates.js
js/components/checkbox.js
js/components/email.js
js/components/input.js
js/components/number.js
js/components/password.js
js/components/radio.js
js/components/telephone.js
js/components/url.js
js/libs/builder.js
js/libs/templates.js
templates/components/checkbox.build.hbs
templates/components/email.build.hbs
templates/components/input.build.hbs
templates/components/number.build.hbs
templates/components/password.build.hbs
templates/components/radio.build.hbs
templates/components/telephone.build.hbs
templates/components/url.build.hbs

ref https://github.com/Fliplet/fliplet-studio/issues/1322
vuejs ref https://github.com/vuejs/vue/issues/6313

field type as static var

---

interface.html

Some copy in the settings section was confusing to several clients recently, updated to be more specific.

Updating settings copy

---

interface.html

Reverts Fliplet/fliplet-widget-form-builder#41

Revert "Updating settings copy"

---

js/libs/builder.js

Fixes: https://github.com/Fliplet/fliplet-studio/issues/1441
Add delete confirmation: https://github.com/Fliplet/fliplet-studio/issues/1430

Fixed issue #1441

---

js/libs/builder.js
js/libs/form.js

- Cleanup for legacy options
- Fixes templates to be sent to users

Fixes legacy issues

---

js/libs/builder.js

Action on link provider should be screen.

Default action when take user to another screen

---

js/build.templates.js
js/components/checkbox.js
templates/components/checkbox.build.hbs

ref https://github.com/Fliplet/fliplet-studio/issues/1318

fix for only one required checkbox

---

js/libs/builder.js

follows https://github.com/Fliplet/fliplet-widget-form-builder/pull/52
ref https://github.com/Fliplet/fliplet-studio/issues/1510

wait for hooks update before save

---

js/libs/builder.js

Fixes https://github.com/Fliplet/fliplet-studio/issues/1510

Fixes email templates being saved empty

---

css/builder.css
interface.html

Tightened up padding and layout to be more compact.

Cleaned up form builder UI to be more compact

---

js/libs/form.js

ref https://github.com/Fliplet/fliplet-studio/issues/1556

only send email when service not bound to a data source

---

css/builder.css
css/form.css
js/build.templates.js
templates/components/starRating.build.hbs

Fixes issue https://github.com/Fliplet/fliplet-studio/issues/1644

Fixes text direction on star rating

---

interface.html

ref https://github.com/Fliplet/fliplet-studio/issues/1689

avoid the "autoscroll" to top when clicking on links

---

js/components/image.js

Fixes https://github.com/Fliplet/fliplet-studio/issues/1684

Fixes getting photo library on Android

---

js/components/image.js

Render image with right type

---

js/libs/form.js

ref https://github.com/Fliplet/fliplet-studio/issues/1810
```js
// the "get()" accepts the form name in case you have multiple forms on the page 
Fliplet.FormBuilder.get().then(function (form) {
// get the input value
form.field('foo').val();
// set the input value
form.field('foo').val('bar');
});
```

public apis

---

js/libs/form.js

ref https://github.com/Fliplet/fliplet-studio/issues/1815

bugfix for progress

---

js/build.templates.js
templates/components/field.build.hbs

Fix for https://github.com/Fliplet/fliplet-studio/issues/1812

Paragraph and other non-field elements won't have the label div element

---

js/libs/form.js

ref https://github.com/Fliplet/fliplet-studio/issues/1834

only edit entries using online data

---

js/libs/form.js

ref https://github.com/Fliplet/fliplet-studio/issues/1932

wait for communication stuff before navigating

---

css/builder.css
interface.html
js/libs/builder.js

ref https://github.com/Fliplet/fliplet-studio/pull/1940

Chore overlay

---

css/builder.css
interface.html
js/libs/builder.js

Added Edit data btn

---

interface.html
js/libs/builder.js

*Note:* I have hidden the *Edit Data* button that for some reason was already in the `master` branch and it shouldn't, until we release the the Studio changes.
This fixes: https://github.com/Fliplet/fliplet-studio/issues/1950

Fixes issue #1950

---

build.html
css/form.css

- Removed overlay colour
- Added opacity to form when in loading/retrieving data state
- Tweaks to CSS from changes made to markup
- Part of changes in https://github.com/Fliplet/fliplet-theme-default/pull/9

Loading state styles

---

js/libs/builder.js

Tinymce updated

---

js/libs/form.js

`form.data()` now returns the form settings.

export form data

---

css/form.css

Adjusts checkbox and radio checked icon size

---

js/components/image.js

For https://github.com/Fliplet/fliplet-studio/issues/2229

Fix: Windows supports only two options on dialog boxes

---

css/builder.css
js/components/file.js
js/components/image.js
js/interface.templates.js
js/libs/core.js
templates/configurations/file.interface.hbs
templates/configurations/image.interface.hbs

- Added support to open the File Manager in an overlay and show the contents of the selected folder
- Image field
- File field

Open file manager from Image and File fields' settings

---

js/libs/builder.js

- This fixes issue with some settings being reset once the overlay is closed

Open file manager - Fixes

---

interface.html

ref https://github.com/Fliplet/fliplet-studio/issues/2334

fixes an incorrect merge

---

css/form.css

Fix https://github.com/Fliplet/fliplet-studio/issues/2364

Fixes issue #2364

---

css/form.css

Ref. https://github.com/Fliplet/fliplet-studio/issues/2380

Forces radio and checkbox transitions to render through GPU

---

js/build.templates.js
js/components/date.js
js/components/time.js
js/configurations/time.js
js/interface.templates.js
templates/components/time.build.hbs
templates/configurations/time.interface.hbs
widget.json

time picker

---

js/libs/builder.js

ref https://github.com/Fliplet/fliplet-studio/issues/2403 https://github.com/Fliplet/fliplet-studio/issues/2401

fix for numbering

---

js/libs/form.js

```js
form.load(function () {
return { a: 1, b: 2 };
});
```
Works also with a promise.

support for loading an entry

---

css/form.css

Moves position of checkbox and radio icons by 1px

---

css/form.css
js/build.templates.js
js/components/file.js
templates/components/file.build.hbs

ref https://github.com/Fliplet/fliplet-studio/issues/2549

fixes for attaching files

---

js/libs/form.js

```js
form.field('foo').options([ 'hello', 'world'  ]);
form.field('foo').options([ { id: 'hello', disabled: true }, { value: 'world' }  ]);
```

public method to set up form field options

---

js/components/image.js

ref https://github.com/Fliplet/fliplet-studio/issues/2683
and I still don't understand why this `forcedClick` thingy is necessary... @tonytlwu you might want to explain :)

fix for getting pictures on native

---

js/components/signature.js

ref https://github.com/Fliplet/fliplet-studio/issues/2738

only reset signature when width changes

---

css/form.css

Adds support for RTL with checkboxes and radios

---

js/libs/form.js

ref https://github.com/Fliplet/fliplet-studio/issues/2894

avoid updating when there's no entryId

---

js/libs/form.js

ref https://docs.google.com/spreadsheets/d/1ITLCZm9fg_A-LIYQDbJsNyTWqPFyF0_25F6-cIR9Z84/edit?ts=5b6ca727#gid=0

don't track reset event after submitting the form

---

js/libs/builder.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/3039#issuecomment-422929520
Fixed as shown below

Ensures form submission redirect options are rendered

---

css/form.css
js/build.templates.js
js/components/signature.js
js/components/wysiwyg.js
templates/components/field.build.hbs
templates/components/wysiwyg.build.hbs
vendor/bootstrap-datepicker3.css

- Moves dropdown triangle position for datepicker
- Adds support for `.has-error` for validation
- Styles WYSIWYG and Signature field appearances to fit with all other fields
- Corrects validation for WYSIWYG and Signature fields

Tweaks styling and validation of date, WYSIWYG and signature fields

---

css/builder.css

Issue reference: https://github.com/Fliplet/fliplet-e2e-tests/issues/223

Prevent settings to be seen underneath the top header

---

js/libs/form.js

for @hcarneiro 
```js
Fliplet.FormBuilder.getAll().then(function (forms) {
});
```

get all forms in a screen

---

js/build.templates.js
js/components/number.js
templates/components/number.build.hbs

ref https://github.com/Fliplet/fliplet-studio/issues/3776
---
https://stackoverflow.com/questions/19233415/how-to-make-type-number-to-positive-numbers-only

don't allow negative numbers when required

---

js/build.templates.js
js/components/starRating.js
templates/components/starRating.build.hbs

ref https://github.com/Fliplet/fliplet-studio/issues/3741
milestone https://github.com/Fliplet/fliplet-studio/milestone/7
---
Stackoverflow ref on required for radio inputs: https://stackoverflow.com/questions/8287779/html5-how-to-use-the-required-attribute-with-a-radio-input-field

support for required attribute on star rating

---

js/components/image.js
js/libs/form.js

- Allows thumbnail to be seen when an image is already set

fixes for image replacement thumbnail

---

css/form.css

Ref. https://github.com/Fliplet/fliplet-studio/issues/3731

Improves radio and checkbox centering to be more precise

---

js/libs/form.js

ref https://github.com/Fliplet/fliplet-studio/issues/4159
---
```js
Fliplet.Hooks.on('beforeFormSubmit', function (data, form) {
})
Fliplet.Hooks.on('afterFormSubmit', function (result, form) {
})
```

add form instance on hooks fired

---

js/components/number.js

ref https://github.com/Fliplet/fliplet-studio/issues/4148

decimals 0 means no decimals

---

js/components/wysiwyg.js

ref https://github.com/Fliplet/fliplet-studio/issues/4328

allow non-html content to be set on wysiwyg

---

js/libs/form.js

ref https://github.com/Fliplet/fliplet-studio/issues/4328#issuecomment-492150670

ensure on load entry error, message gets displayed

---

js/libs/form.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4416

Ensure fields are readable when binding data from profile

---

js/components/file.js

ref https://github.com/Fliplet/fliplet-studio/issues/3783
---
requires https://github.com/Fliplet/fliplet-api/pull/3378

upload files as binary through multipart

---

css/builder.css
js/interface.templates.js
templates/configurations/form.interface.hbs

Ref. https://github.com/Fliplet/fliplet-studio/issues/4313

Updates field configuration form button from "Save" to "Done"

---

js/components/wysiwyg.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/3496

Paste as plaintext by default

---

js/components/wysiwyg.js

ref https://github.com/Fliplet/fliplet-studio/issues/4398

fix for value not initialising after tinymce

---

js/libs/form.js
widget.json

Task Form Builder date field adds unwanted timestamp data, output should be YYYY-MM-DD e.g. 2019-06-11 #4327
Removed unwanted timestamp from date field.
[Screenshot](https://drive.google.com/file/d/1VQCsNgxYuLux86DEp_icBq3C6P7sQUzX/view?usp=sharing)

Date field 4327

---

js/build.templates.js
js/components/checkbox.js
js/components/radio.js
js/components/select.js
js/libs/core.js
templates/components/checkbox.build.hbs
templates/components/radio.build.hbs
templates/components/select.build.hbs

@squallstar 
When configuring a select, option or checkbox field add the ability to set a value not just a name
No ref to the GitHub issue

Set values for the options

---

js/components/wysiwyg.js

Reverts Fliplet/fliplet-widget-form-builder#179

Revert "Paste as plaintext by default"

---

interface.html

@squallstar 
Fixed issue that 'Need help?' link does not lead anywhere. 
Added href link in interface.html 
ref Fliplet/fliplet-studio#3103

#63 [Form builder] 'Need help?' link in form builder settings is not leading anywhere #3103

---

js/libs/form.js

```js
// get form fields
var fields = form.fields.get();
// set fields programmatically
form.fields.set([]);
```

methods to get and set form fields

---

js/components/image.js
templates/components/image.build.hbs

@squallstar 
ref https://github.com/Fliplet/fliplet-studio/issues/3125

Image field thumbnail is incorrectly updated fixed

---

js/libs/builder.js

@squallstar 
**Fixed behavior:** 
The issue here is that the form builder is somehow submitting an empty value for a column called "buttons" (alongside the rest of the values from the fields), when it shouldn't.
ref https://github.com/Fliplet/fliplet-studio/issues/1659

Removed the 'buttons' column in the data source

---

js/libs/form.js

@squallstar 
ref https://github.com/Fliplet/fliplet-studio/issues/4729
video: https://cl.ly/837b450e5ad3

fixed submit form on the enter keydown

---

js/components/number.js

@squallstar 
fixed regExp
ref https://github.com/Fliplet/fliplet-studio/issues/4439

fixed decimal 4439

---

css/builder.css
js/components/file.js
js/components/image.js

ref https://github.com/Fliplet/fliplet-studio/issues/4795

fixes for file field when dealing with strings

---

js/libs/builder.js
js/libs/form.js

ref https://github.com/Fliplet/fliplet-studio/issues/4322

Form instance-exclusive hooks

---

js/libs/builder.js
js/libs/form.js

I've rewritten https://github.com/Fliplet/fliplet-widget-form-builder/pull/222 after deciding to go for a different more robust approach

Refactor for hooks

---

js/components/signature.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4819

Prevent signature field from clearing when activating keyboard for the first time

---

js/components/wysiwyg.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4703

Ensure "Rich text" field type is able to correctly load values from data source

---

js/libs/form.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/5208

Removes empty data from retrieved entry before loading to avoid errors with form fields

---

js/libs/form.js

ref https://github.com/Fliplet/fliplet-studio/issues/5235

ensure array fields do not mutate when the form resets

---

js/components/wysiwyg.js
js/libs/form.js

https://github.com/Fliplet/fliplet-studio/issues/5287
https://github.com/Fliplet/fliplet-studio/issues/5280
https://github.com/Fliplet/fliplet-studio/issues/5286
https://github.com/Fliplet/fliplet-studio/issues/5285
https://github.com/Fliplet/fliplet-studio/issues/5282
https://github.com/Fliplet/fliplet-studio/issues/5274
https://github.com/Fliplet/fliplet-studio/issues/5275
https://github.com/Fliplet/fliplet-studio/issues/5276
Added validation for data that we take from the data source
Rich text
Upload file
Date picker
Time picker
Checkbox
Radio button
Star rating

Added validation for data that we take from the data source

---

js/libs/form.js

https://github.com/Fliplet/fliplet-studio/issues/5466
Fixed validation for radio and star rating

Fixed validation for radio and star rating

---

js/libs/core.js

ref https://github.com/Fliplet/fliplet-studio/issues/5551

fixed code for IE11

---

js/libs/builder.js

https://github.com/Fliplet/fliplet-studio/issues/5642
Updated prompt modal to Fliplet modal.

Updated prompt modal

---

js/components/url.js

Length updated to cover all TLDs http://data.iana.org/TLD/tlds-alpha-by-domain.txt
ref https://github.com/Fliplet/fliplet-studio/issues/5882

update regexp for URLs

---

js/libs/form.js

ref https://github.com/Fliplet/fliplet-studio/issues/4781

update the user's session after updating the profile

---

css/form.css

Reverts Fliplet/fliplet-widget-form-builder#274

Revert "Date and calendar icons are now visible on ios13"

---

js/components/wysiwyg.js

ref https://github.com/Fliplet/fliplet-studio/issues/6149
```js
Fliplet.Hooks.on('beforeRichFieldInitialize', function (data) {
// data.field
// data.config
});
```

added new beforeRichFieldInitialize hook on tinymce init

---

js/libs/form.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/6240

Do not submit invalid date formats from date fields

---

js/libs/form.js

refs https://github.com/Fliplet/fliplet-studio/issues/6643 https://github.com/Fliplet/fliplet-studio/issues/6546

[Fix] fix for form populating and saving paragraph and title

---

css/form.css

Ref. https://github.com/Fliplet/fliplet-studio/issues/5325

[Fix] Ensures calendar icon is displayed in the date picker field

---

interface.html
js/libs/builder.js

https://github.com/Fliplet/fliplet-studio/issues/6757
Removed warning and js associated with it. 
https://streamable.com/xi56tp

[Fix] Removed warning

---

js/components/wysiwyg.js

Fliplet/fliplet-studio#6422
Added accessibility to tinymce editor
https://streamable.com/fdf290

[Fix] Added accessibility to tinymce editor

---

css/builder.css
interface.html
js/libs/builder.js

https://weboo.atlassian.net/browse/OD-10
Integrated data source provider into the form builder
https://share.getcloudapp.com/7KuLKQLx

[Feature] Integrated data source provider into the form builder

---

js/libs/form.js

https://weboo.atlassian.net/browse/OD-122
Update value for the date every time
https://share.getcloudapp.com/p9uwj06R

[Fix] OD-122 Datepicker will show correct date when we use field.set()

---

js/libs/form.js

https://weboo.atlassian.net/browse/OD-51
Check if `Always autofill with current date` selected and show the current date then.
https://share.getcloudapp.com/OAuJw5Kq

[Fix] OD-50 Showing current date/time if option is selected even if data source is connected.

---

js/components/signature.js
js/libs/form.js

- Removes changes done in aada76d4ef84a90de6cf5309250fb7a9d54c30cd and a3fb5d3dce2f7880fc8078040a3a3e3b0d2371e0
- Adds generated filename for signature only
---
Tests:

ID-328 [Fix] Do not hardcode filename for all uploaded files

---

js/components/date.js
js/libs/form.js

https://weboo.atlassian.net/browse/OD-122
Now the calendar will be showing the correct date after `set()`.
https://share.getcloudapp.com/nOunnXK8

[Fix] OD-122 Date picker will show correct date when we use set()

---

js/components/date.js

Ref. https://weboo.atlassian.net/browse/ID-351

ID-351 [Fix] Fixes ES6 syntax that breaks the form feature for Internet Explorer

---

js/components/date.js

https://weboo.atlassian.net/browse/ID-351

Release to Production

---

package-lock.json
package.json

follows https://github.com/Fliplet/fliplet-widget-form-builder/pull/340

[Chore] Forces ES5

---

js/libs/form.js

Ref. https://weboo.atlassian.net/browse/ID-379

ID-379 [Feat] Adapt field data so checkbox and non-checkbox fields can support more data types

---

js/libs/form.js

Ref. https://weboo.atlassian.net/browse/ID-380

ID-380 [Fix] Ensure star rating fields are loaded with data

---

js/libs/form.js

Ref. https://weboo.atlassian.net/browse/ID-379
Follows #343

ID-379 [Feat] Handle arrays for different field types

---

.gitignore
js/components/date.js

https://weboo.atlassian.net/browse/OD-122
Showing current date on date picker init
https://share.getcloudapp.com/L1uQAXNW
The old fix for OD-122 is still working

OD-122 [Fix] Showing current date on date picker init

---

css/builder.css
interface.html
js/libs/form.js

Microrelease to producton

---

js/libs/form.js

Adds similar support to https://github.com/Fliplet/fliplet-api/pull/4384 for using `Fliplet.FormBuilder.getAll(name)` with a query.

[Feat] Adds support for query in Fliplet.FormBuilder.getAll()

---

js/libs/builder.js

OD-299 https://weboo.atlassian.net/browse/OD-299
Fix saving, changing saved button label text for overlays, changing back save button label text for widget.
https://monosnap.com/file/KecSpwUlrngIEAc9EpTLdtRwUfyTt2
@upplabs-alex-levchenko @YaroslavOvdii

OD-299 [Fix] Don't close overlay after clicking on 'Save'

---

js/libs/builder.js
js/libs/templates.js

OD-174 https://weboo.atlassian.net/browse/OD-174
- Retired the template browser in the form component
- Added if condition to check if user has organization templates
- Removed "Enquiry" template
http://somup.com/crn36UDw6O
@upplabs-alex-levchenko @YaroslavOvdii

OD-174 [Feature] Retired the template browser in form component

---

js/libs/builder.js

OD-397 https://weboo.atlassian.net/browse/OD-397
Make form don't break column order in datasource with new fields in form
https://monosnap.com/file/Qmj2ocHhOCV7bXaya8XddGYgbijlMW
@upplabs-alex-levchenko @AndrRyaz @YaroslavOvdii

OD-397 [Fix] Make form don't break column order in datasource with new fields in form

---

js/libs/builder.js

Reverts Fliplet/fliplet-widget-form-builder#368

Revert "OD-397 [Fix] Make form don't break column order in datasource with new fields in form"

---

js/components/date.js

Ref. https://weboo.atlassian.net/browse/ID-1123
This reverts commit b8ad17dedde20bbc8ca9b8016fe48c43aaeb41d1 from https://github.com/Fliplet/fliplet-widget-form-builder/pull/379

ID-1123 [Fix] Ensures date is submitted as selected by the user

---

js/components/wysiwyg.js

Ref. https://weboo.atlassian.net/browse/ID-1131

ID-1131 [Fix] Only initiate mobile editor if the WYSIWYG is not readonly

---

js/components/wysiwyg.js

Ref. https://weboo.atlassian.net/browse/ID-1131

ID-1131 [Fix] Ensures Rich Text form fields are readonly on mobile

---

js/components/date.js

@sofiiakvasnevska @inna-bieshulia
OD-568 https://weboo.atlassian.net/browse/OD-568
Fixed default option for the Date picker field
https://storyxpress.co/video/ks91mdmjfgyjrlcki
@upplabs-alex-levchenko @S-Volodymyr

OD-568 [Fix] Update default option for the Date field

---

css/builder.css
css/form.css

Ref. https://weboo.atlassian.net/browse/ID-1171 https://weboo.atlassian.net/browse/ID-1095
Also includes CSS linting
* Clean up UI so the divider line lines up with the input height
* Removes duplicated clock icon

ID-1171 ID-1095 [Fix] Tidies up time picker UI

---

interface.html
js/libs/builder.js

@sofiiakvasnevska @inna-bieshulia
OD-622 https://weboo.atlassian.net/browse/OD-622
“Add column to data source” - if there's only 1 column to add
”Add columns to data source” - if there is more than 1 column to add
https://storyxpress.co/video/ku58pubcik3jl6er1

OD-622 [Feature] The button text varies depending on the count of non-existent columns

---

js/components/email.js
js/libs/builder.js
js/libs/form.js

@romanyosyfiv
OD-617 https://weboo.atlassian.net/browse/OD-617
**Problem**: Saved e-mails can contain invisible characters. When a user tried to edit an e-mail with invisible characters, the e-mail was invalid. It did not allow to save the form data
**Solution**: The e-mail is checked for invalid characters and deleted

OD-617 [Fix] Added invisible character check

---

js/components/file.js
js/components/image.js
js/components/number.js

- Follows https://github.com/Fliplet/fliplet-widget-form-builder/pull/439

ID-2291 [Fix] Delay form initialization for translations (2/2)

---

js/components/date.js
js/components/time.js

Ref. https://weboo.atlassian.net/browse/ID-2378

ID-2378 [Fix] Prevent required date/time fields from resetting

---

js/components/date.js
js/components/time.js

Ref. https://weboo.atlassian.net/browse/ID-2377

ID-2377 [Fix] Correctly setting submission date/time

---

js/components/date.js
js/components/time.js
js/libs/form.js

Ref. https://weboo.atlassian.net/browse/ID-2382
Requires https://github.com/Fliplet/fliplet-api/pull/5427

ID-2382 [Fix] Fixes date and time field reset behavior to be consistent with other fields

---

js/components/signature.js
js/libs/form.js

Ref. https://weboo.atlassian.net/browse/ID-2424
See https://weboo.atlassian.net/browse/ID-2424?focusedCommentId=33327 for detailed list of changes

ID-2424 [Fix] Refactors validation and submission flow for signature field

---

js/libs/builder.js

- form builder template
-  Organization name rename from `organisationName` to `organizationName`
XOR-53
https://user-images.githubusercontent.com/107605720/199312201-aa3423ab-9159-40db-b200-d3ad8cc9895e.mp4

XOR-53 [FIX] Form email template handlebars for adding app name and organization name working now

---

js/libs/form.js

Widgets -> Add Form -> Add Fields -> Add DS to Form settings
Widgets -> Add List from DS(LFD) -> select same DS as Form in settings
Implemented code to enable empty fields which are not required can be submitted when it's loaded from LFD
[JIRA](https://weboo.atlassian.net/browse/XOR-703)
https://user-images.githubusercontent.com/108272606/203809249-b7c5668b-ab71-4af9-8d02-ac984b98ae8c.mp4
None
None
None

XOR-703 [FIX] Ensure empty fields submitted if not its required when it is loaded from LFD

---

js/libs/core.js

Studio -> Form -> Date / Time field
Implemented code to save date / time picker fields when specific date / time isn't selected
[click here](https://weboo.atlassian.net/browse/XOR-849)
**Result**
https://user-images.githubusercontent.com/108272606/213990200-7d81f5ec-2504-4f2c-89f1-90f75d5cb0d2.mp4
**Checklist**
None
None
None
None

XOR-849 [FIX] Ensure Date picker & Time picker fields can be saved when specific date(time) isn't selected

---

js/build.templates.js
js/libs/core.js
templates/components/field.build.hbs

Widgets -> Form  -> Checkbox / Radio field 
Implemented fix so that in Form component, when user try to click the label of the Checkbox, it's not affecting the previous checkbox option
[JIRA](https://weboo.atlassian.net/browse/XOR-638)
https://user-images.githubusercontent.com/108272606/228465680-31895af8-0a0c-49af-96f4-9ed038e0bce6.mp4
none
none
none
none

XOR-638 [Fix] Ensure when user try to click the label of the Checkbox , its not affecting the previous checkbox option

---

js/libs/form.js
package-lock.json
package.json

Ref. https://weboo.atlassian.net/browse/ID-2956
- Enable ESLint on form.js
- Update ESLint config version

ID-2956 [Maintenance] Enable ESLint on form.js

---

js/libs/form.js
main.yml

Ref. https://weboo.atlassian.net/browse/ID-2956

ID-2956 [Maintenance] Add ESLint to GitHub actions

---

js/components/file.js
js/libs/form.js

Studio -> Form -> File / Image
Implemented code to make sure TypeError is not coming when attaching image file to the Attach file form field
[click here](https://weboo.atlassian.net/browse/XOR-928)
**Result**
https://user-images.githubusercontent.com/108272606/230584447-48cf9786-0ae8-4929-96a8-293d8375dafe.mp4
**Checklist**
None
None
None
None

XOR-928 [FIX] Avoid errors when attaching image (. jpg) file to the file upload field

---

schema.json

Requires https://github.com/Fliplet/fliplet-api/pull/5715

[WIP] ID-2966 [Feat] Adds schema for validation

---

js/components/dateRange.js

ID-3040 [FIX] Restore predefined range field on clear for date range field

---

js/components/checkbox.js
js/libs/form.js

Studio -> Form -> JS API 
Implemented code so that in Form component, The JS API code's Clear button is not working as expected
**Result**
https://github.com/Fliplet/fliplet-widget-form-builder/assets/108272606/315bd9f1-f278-4060-aaee-4c38c0f110a2
**Checklist**
None
None
None
None

ID-3211 [FIX] Ensure in Form component, The JS API code's Clear button is not working as expected

---

js/components/url.js

Ref. https://weboo.atlassian.net/browse/ID-3370

ID-3370 [Fix] Consider the URL as a valid string format if there's no value provided

---

js/libs/form.js

Ref. https://weboo.atlassian.net/browse/ID-3368

ID-3368 [Fix] Prevent error when dropping a new form instance

---

js/components/matrix.js
js/libs/core.js
js/libs/form.js

Studio -> Form -> Form Fields -> Matrix field
Implemented code, so Matrix field will load default value when Link Query parameter option is selected.
[click here](https://weboo.atlassian.net/browse/ID-3362)
**Result**
https://github.com/Fliplet/fliplet-widget-form-builder/assets/108272606/379f96a0-be32-4f27-ab44-0fa29eae8ee3
**Checklist**
None
None
None
None

ID-3362 [FIX] Ensure Matrix field default value displayed when "Link query parameter" option is selected

---

js/components/file.js
js/components/image.js
js/components/signature.js
js/libs/core.js
js/libs/templates.js

Ref. https://weboo.atlassian.net/browse/ID-3444

ID-3444 [Maintenance] Fixes ESLint issues

---

css/form.css

One of the fields with the same size has `own` property.

ID-3521 [FIX] Fields have different sizes when sharing and not sharing the row with the same width

---

js/components/codeScanner.js

https://github.com/Fliplet/fliplet-widget-form-builder/assets/128052346/95cc68af-ae8e-4b1c-ae95-dce704e981b3

ID-3569 [FIX] Ensure code scanner saves correct value

---

build.html
js/components/typeahead.js
js/libs/core.js
js/libs/form.js

https://github.com/Fliplet/fliplet-widget-form-builder/assets/128052346/0bf3e9b6-e8d7-431d-a187-7fcc9b1ecc6c

ID-3568 [FIX] Typeahead newly added values in DS disappear and can’t be selected

---

css/form.css

https://github.com/Fliplet/fliplet-widget-form-builder/assets/128052346/ad4b87ee-a089-4eb8-9003-80b4f439e365

ID-3571 [FIX] Fixes form components' width to match container size

---

build.html

ID-3604 [FIX] Ensure form error message has full width

---

js/components/matrix.js

https://github.com/Fliplet/fliplet-widget-form-builder/assets/128052346/be8377fb-eee8-4e5b-895b-51708ff6c9d8

ID-3732 [FIX] Form is not submitted when matrix field is required and form includes time/date range fields

---

js/components/geolocation.js
js/libs/form.js

ID-3480 [FIX] Add a separate column for location accuracy

---

js/build.templates.js
templates/components/typeahead.build.hbs

Ref. https://weboo.atlassian.net/browse/ID-3771

ID-3771 [FIx] Updates default placeholder value

---

.github/workflows/main.yml
main.yml

fliplet-widget-form-builder
Updated the Node JS version to 18 in GitHub Action workflow file.

Updated GitHub Action Node JS version to 18

---

js/components/select.js

https://github.com/Fliplet/fliplet-widget-form-builder/assets/128052346/5e554cec-d426-4dc7-9f50-fbc70cf26ce0

ID-3865 [FIX] Ensure dropdown field gets/resets correct default value from user profile data

---

js/libs/form.js

https://github.com/Fliplet/fliplet-widget-form-builder/assets/128052346/7a0a2935-e3d6-4b4b-a787-d76966e51a5e

ID-3866 [FIX] Ensure checkbox field gets the default value from storage on reset

---

js/components/wysiwyg.js

https://github.com/Fliplet/fliplet-widget-form-builder/assets/128052346/4ab6ce21-7983-4437-9b89-9ff3cc18580d

ID-3873 [FIX] Ensure rich text has floating toolbar on native apps

---

js/libs/form.js

Ref. https://weboo.atlassian.net/browse/ID-3833
Requires https://github.com/Fliplet/fliplet-api/pull/6004

ID-3833 [Fix] Waits for widget initializations to be ready before returning instances

---

.github/workflows/main.yml
js/components/select.js
js/components/wysiwyg.js
js/libs/form.js
main.yml

| Title | Owner | PR |
| --- | --- | --- |
ID-3849 [FIX] Ensure to close the toolbar in full screen on mobile preview | AS | https://github.com/Fliplet/fliplet-widget-form-builder/pull/595
ID-3865 [FIX] Ensure dropdown field gets/resets correct default value from user profile data | AS | https://github.com/Fliplet/fliplet-widget-form-builder/pull/597
ID-3866 [FIX] Ensure checkbox field gets the default value from storage on reset  | AS | https://github.com/Fliplet/fliplet-widget-form-builder/pull/596
ID-3833 [Fix] Waits for widget initializations to be ready before returning instances | TW | https://github.com/Fliplet/fliplet-widget-form-builder/pull/601
Updated GitHub Action Node JS version to 18 | AS | https://github.com/Fliplet/fliplet-widget-form-builder/pull/599

Release 20240131

---

.github/workflows/main.yml
js/components/select.js
js/components/wysiwyg.js
js/libs/form.js
main.yml

Reverts Fliplet/fliplet-widget-form-builder#606

Revert "Release 20240131"

---

css/form.css
js/components/wysiwyg.js
js/libs/form.js

https://weboo.atlassian.net/browse/ID-4020
https://weboo.atlassian.net/browse/ID-3977
https://weboo.atlassian.net/browse/ID-4051

Release 20240223

---

js/components/wysiwyg.js

ID-3982 [FIX] Ensure mobile supports all the plugins available on the web

---

css/form.css

Reverts Fliplet/fliplet-widget-form-builder#621
due to failed QA

Revert "ID-4120 [FIX] Ensure to not have scroll bar when using TinyMCE 4+ version"

---

js/components/input.js

It prevents resetting the value of read-only input.
[ID-4052](https://weboo.atlassian.net/browse/ID-4052)
[ID-4052]: https://weboo.atlassian.net/browse/ID-4052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ID-4052): prevent resetting value of read only input

---

js/components/input.js

Reverts Fliplet/fliplet-widget-form-builder#625
due to qa failed

Revert "fix(ID-4052): prevent resetting value of read only input"

---

js/components/wysiwyg.js

https://weboo.atlassian.net/browse/ID-3982

Release 20240318

---

js/components/wysiwyg.js

https://weboo.atlassian.net/browse/ID-3976

ID-3976 [FIX] Update field value while undoing and redoing (#604)

---

js/components/customButton.js

https://www.loom.com/share/09df23be66d046429f7da23e4ffac48a?sid=3374db82-7f83-41f9-a51c-19aacd0cdd46

ID-4185 [FIX] Ensure to have variables in custom function context

---

css/form.css
js/components/wysiwyg.js

https://www.loom.com/share/16bad77e29c747789070bf4acdff00eb?sid=41377092-be5e-483f-8a6e-96b276a022aa

ID-4124 [FIX] Ensure to have more tools in Desktop view

---

css/builder.css

Title | Ticket | PR
-- | -- | --
Tweaks data source provider layout and spacing | ID-4372 | x

Release 20240514

---

js/components/wysiwyg.js
js/libs/builder.js

https://weboo.atlassian.net/browse/PS-159

fix(PS-159): removed tiny mce deprecated settings

---

css/form.css
js/components/customButton.js

Form Buider
Ensures Form buttons line up
[PS-339](https://weboo.atlassian.net/browse/PS-339)
[PS-339]: https://weboo.atlassian.net/browse/PS-339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PS-339 [FIX] Ensure Form buttons line up

---

css/form.css

Form Buider, form.css
Ensures custom button is in line with form fields
[ID-4527](https://weboo.atlassian.net/browse/ID-4527)
[ID-4527]: https://weboo.atlassian.net/browse/ID-4527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ID-4527 [FIX] Adjust custom button to be in line with form fields

---

js/libs/builder.js

Reverts Fliplet/fliplet-widget-form-builder#682 due to QA fail.

Revert "PS-53 [FIX] Ensure Rich text field is rendered in Drag and drop accor…"

---

js/libs/core.js

Fliplet Form Builder, core.js
Adds custom width setting for Address field
[DEV-219](https://weboo.atlassian.net/browse/DEV-219)
[DEV-219]: https://weboo.atlassian.net/browse/DEV-219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV-219 [FIX] Add custom width setting for Address field

---

js/libs/core.js

Form Buider 
Adds “custom width” setting for Reorder list field
[DEV-220](https://weboo.atlassian.net/browse/DEV-220)
[DEV-220]: https://weboo.atlassian.net/browse/DEV-220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV-220 [FIX] Add custom width setting for Reorder list field

---

js/libs/core.js

Ticket: [DEV-220](https://weboo.atlassian.net/browse/DEV-220)
PR: https://github.com/Fliplet/fliplet-widget-form-builder/pull/692
[DEV-220]: https://weboo.atlassian.net/browse/DEV-220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV-220 [FIX] Add custom width setting for Reorder list field (#692)

---

js/build.templates.js
js/components/image.js
templates/components/image.build.hbs
translation.json

Ensures the image is not uploaded and displays an error if it exceeds the maximum size.
[PS-73](https://weboo.atlassian.net/browse/PS-73)
[PS-73]: https://weboo.atlassian.net/browse/PS-73?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PS-73 [FIX]:  Ensures the image is not uploaded and displays an error if it exceeds the maximum size.

---

js/components/timer.js

Ensures Timer field Can stop the timer with Autostart enabled
[PS-447](https://weboo.atlassian.net/browse/PS-447)
[PS-447]: https://weboo.atlassian.net/browse/PS-447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PS-447 [FIX]:  Ensures Timer field Can stop the timer with Autostart enabled

---

js/components/address.js

Ensures Address field is pulling user profile data.
[PS-430](https://weboo.atlassian.net/browse/PS-430)
[PS-430]: https://weboo.atlassian.net/browse/PS-430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PS-430 [FIX] Ensures Address field is pulling user profile data.

---

js/components/date.js

Ensures the form shows and saves a new value after the date is removed by clicking a x icon
[PS-72](https://weboo.atlassian.net/browse/PS-72)
[PS-72]: https://weboo.atlassian.net/browse/PS-72?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PS-72 [FIX] Ensures the form shows and saves a new value after the date is removed by clicking a x icon

---

js/components/address.js

Ticket: [PS-430 ](https://weboo.atlassian.net/browse/PS-430)
PR: https://github.com/Fliplet/fliplet-widget-form-builder/pull/709

PS-430 [FIX] Ensures Address field is pulling user profile data. (#709)

---

build.html
js/libs/form.js

Reverts Fliplet/fliplet-widget-form-builder#715 due to QA fail.

Revert "Fix/DEV-379: Restrict Map field to Admins and Impersonating Users Only"

---

js/libs/builder.js

Fliiplet Form Builder
Ensures the existing DS Hook updates correctly when configuring the Email Template in form settings.
[PS-417](https://weboo.atlassian.net/browse/PS-417)
[PS-417]: https://weboo.atlassian.net/browse/PS-417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PS-417 [FIX] Ensures the existing DS Hook updates correctly when configuring the Email Template in form settings.

---

js/components/typeahead.js

Fliiplet Form Builder
Ensures the default value is available for the user when the List of Values is configured.
[PS-279](https://weboo.atlassian.net/browse/PS-279)
[PS-279]: https://weboo.atlassian.net/browse/PS-279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PS-279 [FIX] Ensures the default value is available for the user when the List of Values is configured.

---

js/libs/builder.js

Ticket: [DEV-416](https://weboo.atlassian.net/browse/DEV-416)  [PS-255](https://weboo.atlassian.net/browse/PS-255)
PR: https://github.com/Fliplet/fliplet-widget-form-builder/pull/731
[DEV-416]: https://weboo.atlassian.net/browse/DEV-416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PS-255]: https://weboo.atlassian.net/browse/PS-255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV-416 [FIX] Validates Form displayName Before Use (#731)

---

js/libs/form.js

Quick fix to resolve const variable assignment issue. 
Ticket: [PS-712](https://weboo.atlassian.net/browse/PS-712)
[PS-712]: https://weboo.atlassian.net/browse/PS-712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PS-712 [Fix] Fixed variable assignment issue

---

js/libs/form.js

| Title | Ticket | PR |
|--------|--------|--------|
| Form Builder: Form is not loading. Retrieving data... with "TypeError: Assignment to constant variable." console error| [PS-712](https://weboo.atlassian.net/browse/PS-712) | #736 |
[PS-712]: https://weboo.atlassian.net/browse/PS-712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PS-712 [Fix] Fixed variable assignment issue (#736)

---

js/components/number.js

Tickets: [PS-690](https://weboo.atlassian.net/browse/PS-690)
PR: https://github.com/Fliplet/fliplet-widget-form-builder/pull/763
[PS-690]: https://weboo.atlassian.net/browse/PS-690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PS-690 [FIX]

---

js/libs/builder.js
js/libs/core.js
js/libs/form.js

Ensures form inside the slide is not submitting instead of moving to the next slide
Ensures User cannot swipe between slides with forms that have required fields 
[DEV-516](https://weboo.atlassian.net/browse/DEV-516)
[DEV-504](https://weboo.atlassian.net/browse/DEV-504)
[DEV-516]: https://weboo.atlassian.net/browse/DEV-516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-504]: https://weboo.atlassian.net/browse/DEV-504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix/DEV-516: Ensures form inside the slide is not submitting instead of moving to the next slide

---

css/builder.css
js/interface.templates.js
js/libs/core.js
templates/configurations/paragraph.interface.hbs

Ticket: https://weboo.atlassian.net/browse/DEV-469
PR: https://github.com/Fliplet/fliplet-widget-form-builder/pull/762

DEV-469 [FEAT] add formatting options to paragraph form field (#762)

---

js/components/image.js

Ticket: https://weboo.atlassian.net/browse/PS-962
PR: https://github.com/Fliplet/fliplet-api/pull/7002

release/PS-962: Fix image resizing before upload (#784)

---

js/libs/form.js

Tickets: [PS-1048](https://weboo.atlassian.net/browse/PS-1048) [PS-1060](https://weboo.atlassian.net/browse/PS-1060)
PR: https://github.com/Fliplet/fliplet-widget-form-builder/pull/787
[PS-1048]: https://weboo.atlassian.net/browse/PS-1048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PS-1060]: https://weboo.atlassian.net/browse/PS-1060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PS-1048 [FIX] Ensures the form field is pulling data from DS when editing an existing entry.

---

widget.json

Related Ticket: https://weboo.atlassian.net/browse/PS-1030
PR: #790

PS-1030 [Fix] Updated widget.json to include data-source references within fields

---

css/builder.css
interface.html
js/libs/builder.js
translation.json

Adds warning message when no Datasource is linked or the form is not configured to insert/update entries in the Datasource.
Adds warning message when media folder not configured for any of the relevant fields (File, Image, Signature) 
[PS-1079](https://weboo.atlassian.net/browse/PS-1079)
[PS-1079]: https://weboo.atlassian.net/browse/PS-1079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Release PS-1079
